#!/usr/bin/env python3
"""Bootstrap RollsBar WordPress staging over SSH without exposing secrets.

Reads the staging DB/admin credentials generated by create_staging_database.py
from the hosting user's home directory, writes a short-lived mode-0600 env file,
runs the repository's canonical preflight/bootstrap scripts, performs local
WP-CLI assertions, and removes the temporary env file.

The DaData API token comes only from the GitHub `staging` environment. It is
masked in Actions, transported through the short-lived runtime env file, and
persisted server-side into wp-config.php by bootstrap-staging.sh. It is never
written to Git or rendered into browser JavaScript.

The live REG.RU staging environment has already passed Gate B and was promoted
to the full 118-product catalog. Routine code deploys therefore preserve the
staging database/catalog and must not re-run the historical five-product seed.
The clean ephemeral bootstrap workflow still exercises that smoke-import path.
"""
from __future__ import annotations

import json
import os
import shlex
import socket
from urllib.parse import urlsplit

import paramiko

BASE = os.environ["ISP_MANAGER_URL"].strip()
USER = os.environ["ISP_MANAGER_USER"].strip()
PASSWORD = os.environ["ISP_MANAGER_PASSWORD"].strip()
DADATA_API_KEY = os.environ["ROLLSBAR_DADATA_API_KEY"].strip()
DEPLOY_SHA = os.environ["ROLLSBAR_DEPLOY_SHA"].strip()
CONFIRM = os.environ.get("ROLLSBAR_CONFIRM_BOOTSTRAP_STAGING", "")
SECRET_FILE = ".rollsbar-staging-secrets.json"
RUNTIME_FILE = ".rollsbar-staging-runtime.env"
DOMAIN = "staging.rollsbar.ru"
REPO = "https://github.com/tilaninishi12754-code/rollsbar.git"
EXPECTED_STAGING_PRODUCTS = 118
EXPECTED_WORDPRESS_VERSION = "7.1.3"
EXPECTED_WOOCOMMERCE_VERSION = "11.1.2"


def shell_quote(value: str) -> str:
    return shlex.quote(value)


def connect() -> paramiko.SSHClient:
    host = urlsplit(BASE).hostname or ""
    if not host:
        raise RuntimeError("Could not derive hosting hostname")
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(
        hostname=host,
        port=22,
        username=USER,
        password=PASSWORD,
        timeout=15,
        auth_timeout=15,
        banner_timeout=15,
        look_for_keys=False,
        allow_agent=False,
    )
    return client


def read_secrets(client: paramiko.SSHClient) -> dict[str, str]:
    sftp = client.open_sftp()
    try:
        with sftp.open(SECRET_FILE, "r") as fh:
            data = json.loads(fh.read().decode("utf-8"))
    finally:
        sftp.close()
    required = ("db_name", "db_user", "db_password", "db_host", "wp_admin_password")
    if not all(data.get(key) for key in required):
        raise RuntimeError("Staging secret file is incomplete")
    return data


def mask_dynamic_secrets(data: dict[str, str]) -> None:
    """Register generated and runtime staging secrets with GitHub log masking."""
    values = [data.get("db_password", ""), data.get("wp_admin_password", ""), DADATA_API_KEY]
    for value in values:
        if value:
            print(f"::add-mask::{value}", flush=True)


def write_runtime_env(client: paramiko.SSHClient, data: dict[str, str]) -> None:
    values = {
        "DB_NAME": data["db_name"],
        "DB_USER": data["db_user"],
        "DB_PASSWORD": data["db_password"],
        "DB_HOST": data.get("db_host", "localhost"),
        "WP_ADMIN_PASSWORD": data["wp_admin_password"],
        "WP_ADMIN_USER": "rollsbar_staging_admin",
        "WP_ADMIN_EMAIL": "webmaster@staging.rollsbar.ru",
        "WP_TITLE": "Rolls Bar — Staging",
        "STAGING_URL": f"https://{DOMAIN}",
        "ROLLSBAR_DADATA_API_KEY": DADATA_API_KEY,
        # Gate B has already promoted the real staging DB to all 118 products.
        # Routine deploys must not overwrite client-editable catalog data.
        "ROLLSBAR_IMPORT_SMOKE": "0",
    }
    body = "".join(f"export {key}={shell_quote(value)}\n" for key, value in values.items())
    sftp = client.open_sftp()
    try:
        with sftp.open(RUNTIME_FILE, "w") as fh:
            fh.write(body.encode("utf-8"))
        sftp.chmod(RUNTIME_FILE, 0o600)
    finally:
        sftp.close()


def exec_checked(client: paramiko.SSHClient, command: str) -> str:
    _, stdout, stderr = client.exec_command(command, timeout=420)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    status = stdout.channel.recv_exit_status()
    print(out, end="" if out.endswith("\n") or not out else "\n")
    if status != 0:
        if err:
            safe_lines = [line for line in err.splitlines() if "password" not in line.lower() and "db_" not in line.lower() and "dadata" not in line.lower()]
            if safe_lines:
                print("remote_stderr=" + " | ".join(safe_lines[-8:])[:1200])
        raise RuntimeError(f"Remote bootstrap failed with exit status {status}")
    return out


if CONFIRM != "YES":
    raise SystemExit("Refusing mutation: set ROLLSBAR_CONFIRM_BOOTSTRAP_STAGING=YES")
if len(DEPLOY_SHA) < 7:
    raise SystemExit("ROLLSBAR_DEPLOY_SHA is missing")
if len(DADATA_API_KEY) < 10:
    raise SystemExit("ROLLSBAR_DADATA_API_KEY is missing")

client = None
try:
    client = connect()
    data = read_secrets(client)
    mask_dynamic_secrets(data)
    write_runtime_env(client, data)

    remote = f'''set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"
WP_PATH="$HOME/www/{DOMAIN}"
PROJECT_ROOT="$HOME/.rollsbar-deploy"
RUNTIME="$HOME/{RUNTIME_FILE}"
cleanup() {{ rm -f "$RUNTIME"; }}
trap cleanup EXIT

mkdir -p "$HOME/.local/bin" "$WP_PATH"
if ! command -v wp >/dev/null 2>&1; then
  curl -fsSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o "$HOME/.local/bin/wp"
  chmod 700 "$HOME/.local/bin/wp"
fi
wp --version

if [[ ! -d "$PROJECT_ROOT/.git" ]]; then
  rm -rf "$PROJECT_ROOT"
  git clone --filter=blob:none --no-checkout {shell_quote(REPO)} "$PROJECT_ROOT"
fi
git -C "$PROJECT_ROOT" fetch --depth=1 origin {shell_quote(DEPLOY_SHA)}
git -C "$PROJECT_ROOT" checkout --detach --force {shell_quote(DEPLOY_SHA)}

set -a
source "$RUNTIME"
set +a
export WP_PATH PROJECT_ROOT

echo "deploy_target={DOMAIN}"
echo "deploy_sha={DEPLOY_SHA}"
echo "wp_path=$WP_PATH"
bash "$PROJECT_ROOT/wordpress/deploy/preflight.sh"
bash "$PROJECT_ROOT/wordpress/deploy/bootstrap-staging.sh"

wp --path="$WP_PATH" core is-installed
core_version="$(wp --path="$WP_PATH" core version)"
woo_version="$(wp --path="$WP_PATH" plugin get woocommerce --field=version)"
theme_status="$(wp --path="$WP_PATH" theme get rollsbar-theme --field=status)"
core_status="$(wp --path="$WP_PATH" plugin get rollsbar-core --field=status)"
product_count="$(wp --path="$WP_PATH" post list --post_type=product --post_status=publish --format=count)"
blog_public="$(wp --path="$WP_PATH" option get blog_public)"
dadata_configured="$(wp --path="$WP_PATH" eval 'echo defined("ROLLSBAR_DADATA_API_KEY") && strlen((string) ROLLSBAR_DADATA_API_KEY) >= 10 ? "yes" : "no";')"

echo "assert_core=$core_version"
echo "assert_woocommerce=$woo_version"
echo "assert_theme=$theme_status"
echo "assert_rollsbar_core=$core_status"
echo "assert_products=$product_count"
echo "assert_blog_public=$blog_public"
echo "assert_dadata_server_key=$dadata_configured"
[[ "$core_version" == "{EXPECTED_WORDPRESS_VERSION}" ]]
[[ "$woo_version" == "{EXPECTED_WOOCOMMERCE_VERSION}" ]]
[[ "$theme_status" == "active" ]]
[[ "$core_status" == "active" ]]
[[ "$product_count" == "{EXPECTED_STAGING_PRODUCTS}" ]]
[[ "$blog_public" == "0" ]]
[[ "$dadata_configured" == "yes" ]]
echo "STAGING WORDPRESS DEPLOY PASS"
'''
    exec_checked(client, "bash -lc " + shell_quote(remote))
except (paramiko.SSHException, socket.error, OSError, RuntimeError, ValueError) as exc:
    message = str(exc).replace(PASSWORD, "***").replace(DADATA_API_KEY, "***")
    print(f"staging_bootstrap=failed type={exc.__class__.__name__}")
    print(message)
    raise SystemExit(1)
finally:
    if client is not None:
        try:
            sftp = client.open_sftp()
            try:
                sftp.remove(RUNTIME_FILE)
            except FileNotFoundError:
                pass
            finally:
                sftp.close()
        except Exception:
            pass
        client.close()
